- hosts: all
  roles:

  - role: pcengines-apu2-console

  - role: pcengines-apu2-hostapd
    # country_code
    # ssid
    passphrase: "{{ wpa_passphrase }}"

  - role: nat-masquerade
    interface: eth0

  - role: dhcpd
    interfaces: "{{ dhcpd.interfaces }}"
    networks: "{{ dhcpd.networks }}"

  - role: ipv6-ia-slaac
    uplink: eth0
    interfaces: "{{ ipv6_ia_slaac.interfaces }}"
